using UnityEngine;

public class SimpleTest : MonoBehaviour
{
    private int frameCount = 0;
    
    private void Awake()
    {
        Debug.Log("========================================");
        Debug.Log("游릭 SimpleTest.Awake() CALLED!");
        Debug.Log("========================================");
    }
    
    private void Start()
    {
        Debug.Log("游릭 SimpleTest.Start() CALLED!");
        Debug.Log($"游릭 Time.timeScale = {Time.timeScale}");
        Debug.Log($"游릭 Time.deltaTime = {Time.deltaTime}");
    }

    private void Update()
    {
        frameCount++;
        
        // 햍쮏햦혞햣햪 햨햟햤햢혞혩 혜햣햨혞햫햢혞
        if (frameCount % 60 == 0)
        {
            Debug.Log($"游릭 SimpleTest.Update() is RUNNING! Frame: {frameCount}, Time: {Time.time:F1}s");
        }
        
        // 쮏쒫왐혪햣햪 쒫쒫쮏 먫햎 행햆햇햐햛
        if (Input.anyKeyDown)
        {
            Debug.Log("游릭 SimpleTest detected: Input.anyKeyDown = TRUE");
            
            if (Input.GetKeyDown(KeyCode.UpArrow))
                Debug.Log("游릭游릭游릭 UP ARROW in SimpleTest.Update()!");
            if (Input.GetKeyDown(KeyCode.Space))
                Debug.Log("游릭游릭游릭 SPACE in SimpleTest.Update()!");
        }
        
#if ENABLE_INPUT_SYSTEM
        var keyboard = UnityEngine.InputSystem.Keyboard.current;
        if (keyboard != null)
        {
            if (keyboard.upArrowKey.wasPressedThisFrame)
                Debug.Log("游릭游릭游릭 UP ARROW (New Input) in SimpleTest.Update()!");
            if (keyboard.spaceKey.wasPressedThisFrame)
                Debug.Log("游릭游릭游릭 SPACE (New Input) in SimpleTest.Update()!");
        }
#endif
    }

    private void FixedUpdate()
    {
        // 햍쮏햦혞햣햪 햟향  혜햣햨혞햫햢혞
        if (Time.fixedTime % 1f < Time.fixedDeltaTime)
        {
            Debug.Log($"游릭 SimpleTest.FixedUpdate() is RUNNING! Time: {Time.fixedTime:F1}s");
        }
    }

    private void LateUpdate()
    {
        // 햍쮏햦혞햣햪 햨햟햤햢혦햣 2 혜햣햨혞햫햢혦
        if (frameCount % 120 == 0)
        {
            Debug.Log($"游릭 SimpleTest.LateUpdate() is RUNNING! Frame: {frameCount}");
        }
    }
}
